name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE ([#$NUMBER]($URL))'
template: |
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '⚠ BREAKING CHANGES:'
    label: 'breaking'
  - title: 'Features:'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes:'
    label: 'bug'
  - title: 'Maintenance:'
    labels:
      - 'chore'
      - 'refactoring'
  - title: 'Documentation:'
    label: 'documentation'
  - title: 'Other Changes:'
  - title: 'Dependency Updates:'
    label: 'dependencies'
    collapse-after: 5

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  default: patch