name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# TODO setup aws
# env:
#   RESUME_IAM_ROLE_ARN: ${{ secrets.RESUME_IAM_ROLE_ARN }}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PDF_FILE: docs/職務経歴書.pdf
      OUTPUT_ZIP: docs/resume.zip
      # TODO secretsを使う
      PASSWORD: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: npm ci
      - name: build pdf
        run: npm run build:pdf
      - name: Create zip
        run: zip --encrypt --password ${{ env.PASSWORD }} -j ${{ env.OUTPUT_ZIP }} ${{ env.PDF_FILE }}
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # see https://github.com/release-drafter/release-drafter/issues/900
      - name: Upload Release Asset
        run: |
          gh release upload --clobber ${{ env.VERSION }} ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.release_drafter.outputs.tag_name }}
          FILES: ${{ env.OUTPUT_ZIP }}