name: lint text

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: lint text
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/cache-node-modules
        id: cache-node-modules
      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: lint text
        run: npm run lint